export enum Permissions {
  USER_READ = "USER_READ",
  USER_WRITE = "USER_WRITE",
  ROLE_MANAGE = "ROLE_MANAGE",
  KYC_REVIEW = "KYC_REVIEW",
  TENANT_MANAGE = "TENANT_MANAGE",
  BOOKING_MANAGE = "BOOKING_MANAGE",
  TRANSACTION_READ = "TRANSACTION_READ",
  PAYMENT_READ = "PAYMENT_READ",
  SUPPORT_MANAGE = "SUPPORT_MANAGE",
  ANNOUNCEMENT_MANAGE = "ANNOUNCEMENT_MANAGE",
  CMS_MANAGE = "CMS_MANAGE",
  BLOG_MANAGE = "BLOG_MANAGE",
  SYSTEM_SECURITY = "SYSTEM_SECURITY",
  KYC_APPROVE = "KYC_APPROVE",
  PROVIDER_READ = "PROVIDER_READ",
  SERVICE_MANAGE = "SERVICE_MANAGE",
}

